NAME = tmd
BINDIR = bin
GOBUILD=CGO_ENABLED=0 go build -trimpath -ldflags '-w -s'

all: linux-amd64 darwin-amd64 windows-amd64 # Most used

linux-amd64:
	GOARCH=amd64 GOOS=linux $(GOBUILD) -o $(BINDIR)/$(NAME)-$@

darwin-amd64:
	GOARCH=amd64 GOOS=darwin $(GOBUILD) -o $(BINDIR)/$(NAME)-$@

windows-amd64:
	GOARCH=amd64 GOOS=windows $(GOBUILD) -o $(BINDIR)/$(NAME)-$@.exe

test:
	go test -v ./...

clear:
	rm $(BINDIR)/*