name: Go Release

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "**/*.md"
      - "doc/**"

permissions:
  contents: read

jobs:
  release-build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          $env:GOARCH = "amd64"
          $env:CGO_ENABLED = "0"
          go build -o bin/tmd-${{ runner.os }}-amd64.exe -v -ldflags "-w -s -X github.com/unkmonster/tmd/internal/api.Version=${{ github.ref_name }}" .

      - name: Build for Unix
        if: ${{ matrix.os != 'windows-latest' }}
        shell: bash
        run: |
          GOARCH=amd64 CGO_ENABLED=0 go build -o bin/tmd-${{ runner.os }}-amd64 -v -ldflags "-w -s -X github.com/unkmonster/tmd/internal/api.Version=${{ github.ref_name }}" .

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ runner.os }}
          path: bin/*
          if-no-files-found: error

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: release-build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          path: release-artifacts
          merge-multiple: true

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/*
